version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.7
        environment:
          ENV: CI
          GO111MODULE: "on"
          RAGEL_VERSION: "6.10"
    working_directory: /go/src/github.com/influxdata/cron
    steps:
      - checkout
      - run:
          name: get ragel
          command: |
            cd ../ &&
            curl http://www.colm.net/files/ragel/ragel-${RAGEL_VERSION}.tar.gz -O && \
            tar -xzf ragel-${RAGEL_VERSION}.tar.gz && \
            cd ragel-${RAGEL_VERSION}/ && \
            ./configure --prefix=/usr/local && \
            sudo make && \
            sudo make install
      - run:
          name: check generated code
          command: |
            go generate
            if ! git --no-pager diff --exit-code -- go.mod go.sum; then
              echo generate not generated properly run go generate with ${RAGEL_VERSION}
              exit 1
            fi
      - run:
          name: check tidy
          command: |
            go mod tidy
            if ! git --no-pager diff --exit-code -- go.mod go.sum; then
              echo modules are not tidy, please run 'go mod tidy'
              exit 1
            fi
      - run: go get -v -t -d ./...
      - run: go vet -unreachable=false ./... # ragel generates unreachable code so we ignore this test
      - run: go get honnef.co/go/tools/cmd/staticcheck  && staticcheck ./...
      - run: go test -v --race ./...
